services:
  web:
    container_name: pacha-web
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        DJANGO_ENV: development
    command: python pacha/manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./env/.env.dev
    depends_on:
      - db
    volumes:
      - ./:/code/

  db:
    container_name: pacha-db
    restart: unless-stopped
    image: postgres:latest
    ports:
      - 5432:5432
    env_file:
      - ./env/.env.dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    entrypoint:
      - "/bin/bash"
      - "-c"
      - |
        docker-entrypoint.sh postgres &
        until pg_isready -U postgres; do sleep 3; done &&
        wait

volumes:
  postgres_data:
